name: GitOps pipeline with ArgoCD (pull-based)

on:
  push:
    branches:
      - main

env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }} .

      - name: Scan Docker image with Trivy
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v3
        with:
          repository: phoenix0xff/GitOps
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GIT_USERNAME"
          git config user.email "$GIT_EMAIL"

      - name: Update image tag in deployment.yaml
        run: |
          echo "Before update:"
          grep "image:" manifest/deployment.yaml || true

          sed -i "s+image: $DOCKERHUB_USERNAME/my-app.*+image: $DOCKERHUB_USERNAME/my-app:$GITHUB_SHA+g" manifest/deployment.yaml

          echo "After update:"
          grep "image:" manifest/deployment.yaml || true

      - name: Commit and push updated manifest
        run: |
          git add manifest/deployment.yaml
          git commit -m "Update image to $GITHUB_SHA" || echo "No changes to commit"
          git push origin main