name: GitOps pipeline with ArgoCD (pull-based)

on:
  push:
    branches:
      - main

env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
  GIT_USERNAME: ${{ secrets.GIT_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }} .

      - name: Scan Docker image with Trivy
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v3
        with:
          repository: phoenix0xff/GitOps
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # cant use same access token here as I am accessing another repository
          fetch-depth: 0

      - name: Update deployment.yaml with new image
        run: |
          git config user.name "${{ secrets.GIT_USERNAME }}"
          git config user.email "${{ secrets.GIT_EMAIL }}"

          sed -i "s+image: ${DOCKERHUB_USERNAME}/my-app.*+image: ${DOCKERHUB_USERNAME}/my-app:${GITHUB_SHA}+g" manifest/deployment.yaml

      - name: Verify new image tag in deployment.yaml
        run: |
          if ! grep -q "${{ secrets.DOCKERHUB_USERNAME }}/my-app:${{ github.sha }}" deployment.yaml; then
            echo "Error: deployment.yaml does not contain the new image tag!"
            exit 1
          else
            echo "Image tag verification passed."
          fi

      - name: Commit and push updated deployment.yaml
        run: |
          git add deployment.yaml
          git commit -m "Update image to my-app:${{ github.sha }}"
          git push origin main
